### PR TITLE
lab 4 and 5

### PR DESCRIPTION
**Pull request by intade**

### CODE REVIEW

**Comment by intade** [comment]
I've used firebase as an db. the data to log in as an admin : admin@admin.ru admin1 .
in the telegram we agreed to these points:
Authentication
adding to a card
english and russian language support
rating
product set management (crud)
And all these points were implemented.

https://coffee-b579a.web.app

**Review by gmltA — COMMENTED** [review]
Can you remind me which topic were you implementing?

**Comment by intade** [comment]
it is my own topic : coffee shop

**Review by gmltA — APPROVED** [review]
Okay. That's a <kbd>9</kbd>. What's left?

**Comment by intade** [comment]
Thanks, nothing is left, all points are implemented

**Comment by gmltA** [comment]
If so, I can give you an admission to the exam, but you won't get a recommendation. Do you agree with that?

**Comment by intade** [comment]
And what can i do for the recommendation?

**Review by gmltA — CHANGES_REQUESTED** [review]
1. Add CI (auto deploy).
2. Fix header menu behaviour so that it will collapse when I click outside of it.
3. Add [skeleton](https://material-ui.com/components/skeleton/) placeholders for pages that have async data load.
4. Make language switch work without page reload.

**Comment by intade** [comment]
maybe is there something that i can implement instead of skeleton placeholders?

**Comment by intade** [comment]
What is the total grade for the all labs can you offer me with the admission to the exam? as entry grade

**Comment by intade** [comment]
Okay, no problem. All points were implemented. for adding ci i used netlify and created a new repo https://github.com/intade/6sem-frontent for this, here you go the new link, https://practical-roentgen-4a211f.netlify.app/

**Comment by gmltA** [comment]
And why did you create new repo? And how can I now see code difference between this and that versions?

**Comment by intade** [comment]
Because this repo is with lab1 and index is not in the root for ci. New repo contain the same code as that repo

**Comment by gmltA** [comment]
I won't accept it until you make it here within PR with the code difference between milestones.

**Comment by intade** [comment]
I made a commit with new tasks above - "skeleton, russian/english without refresh and fixing header" where i implemented all points except ci. And new repo is for only ci. You can see the code difference in this repo. I'm a little bit confused...

**Comment by gmltA** [comment]
Can you explain me the difficulties of implementing CI here?

**Comment by intade** [comment]
i configured netlify to autodeploy this repo with that link https://competent-lichterman-1f3c61.netlify.app/ . Difficulties were connected with folder to publish. I entered "frontend" instead of "frontend/"

**Comment by gmltA** [comment]
And you can't reconfigure it to work with this repo?

**Comment by intade** [comment]
i mean i configured with this repo 1 hour ago as you requested

**Review by gmltA — APPROVED** [review]
Okay. Then that's it. Your resulting mark will be <kbd>8</kbd>.

Good luck.

**Pull request merged**
