### PR TITLE
css

### PR DESCRIPTION
**Pull request by intade**
i've done a common index html and others views loaded right in it. I used visual studio code with the "Live Server" extension to write it

### CODE REVIEW

**Comment by intade** [comment]
in the new commit i added lab4 and lab5. I've used firebase as an db. the data to log in as an admin : admin@admin.ru admin1 .
in the telegram we agreed to these points:
Authentication
adding to a card
english and russian language support
rating
product set management (crud)
And all these points were implemented.

**Comment by intade** [comment]
it was so difficult for me to deploy here spa... So i used firebase https://coffee-b579a.web.app

**Comment by gmltA** [comment]
Can you leave only milestone 3 here?

**Comment by intade** [comment]
done

**Comment by intade** [comment]
and now do i have to create new branch for milestones 4 and 5?

**Comment by gmltA** [comment]
> and now do i have to create new branch for milestones 4 and 5?

Indeed.

**Review by gmltA — COMMENTED** [review]
For now I can let you go with <kbd>6</kbd>. To improve it, add `:focus` and `:hover` styles for interactive elements.

**Comment by intade** [comment]
i'm okay with 6

**Review by gmltA — APPROVED** [review]

**Pull request merged**
